### ISSUE TITLE
Support for CSS Grid Layout

### ISSUE THREAD

**Issue by warpech** [cssnext/cssnext#133]
Is support for [CSS Grid](http://www.w3.org/TR/css-grid-1/) considered? 

Do you think it is feasible at all on a transpiler level at all, given that all prior art in this area ([css-grid-polyfill](https://github.com/FremyCompany/css-grid-polyfill), [Grid-Layout-Polyfill](https://github.com/codler/Grid-Layout-Polyfill)) is dynamic JavaScript libraries?

**Comment by MoOx** [comment]
For now cssnext doesn't have a runtime and this thing cannot be handled by a "simple" transformation.
We might discuss about a potential runtime library before wanting to implement this sort of things.
If we start to handle polyfill, this will be like a total different project because:

- require js on client side
- must be light
- must be fast

I am afraid of FOUC. Lot of CSS dev were trolling LESS client runtime, I think we should not do that for such huge feature.
It's like implementing flexbox, seems crazy right ?

**Comment by MoOx** [comment]
Closing due the lack of interest.

**Comment by Paulmicha** [comment]
In case anyone else arrived here looking if cssnext did anything for flexbox, see answers above + https://github.com/7rulnik/postcss-flexibility (for https://github.com/10up/flexibility).

**Comment by jcrben** [comment]
I'd be interested in this but I can imagine that it would be quite the heavy lift.

**Comment by bloodyowl** [comment]
IMO we cannot propose this: 
- polyfills would whether create lots of DOM APIs inconsistencies in metrics (`offset{Top|Left}` for instance) or in DOM structure (addition of elements at runtime)
- having a client-side polyfill in JS doesn't belong in CSS pre/post-processing realm

**Comment by viniciuscb** [comment]
+1

**Comment by garek007** [comment]
+1 !

**Comment by MoOx** [comment]
It's. not. the. responsibility. of. a. postcss. plugin.
