### ISSUE TITLE
Why is CLI global usage "not recommended"?

### ISSUE THREAD

**Issue by awayken** [cssnext/cssnext#150]
In the [Installation section of the Setup page](http://cssnext.io/setup/#installation) of the website, it mentions that installing through `npm` using `-g` is "not recommended." I was wondering why that is. Is it because the recommended usage would be to use cssnext in a build tool or script of some sort, or is there something else to this?

I also noticed that there is no installation bullet point noted as "recommended," so a newcomer might be left confused.

If someone can explain to me the reasons for the notes, I can take a stab at contributing copy to that page to pass the knowledge on.

**Comment by bloodyowl** [comment]
this type of installation isn't recommended because the versions you want across your projects can be incompatible. to prevent this, install cssnext locally and use npm scripts in your package.json:

```json
{
  "scripts": {
    "css": "cssnext src/styles/index.css dist/index.css"
  }
}
```

and then run:

```console
$ npm run css
```

you can also add `./node_modules/.bin` to your `$PATH` to get the right CLI locally.

**Comment by MoOx** [comment]
I will add this to the incoming FAQ
